from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional, Protocol, Union
from pathlib import Path
import torch

class TelemetryObserver(Protocol):
    """Interface for logging, metrics, and progress tracking."""
    def log(self, level: str, message: str) -> None: ...
    def track_metric(self, name: str, value: float, step: int) -> None: ...
    def create_progress(self, desc: str, total: int) -> Any: ...

class Registry(ABC):
    """Interface for artifact persistence (Model, Data, Config)."""
    @abstractmethod
    def save_model(self, state_dict: Dict[str, Any], name: str, tag: str) -> Path: ...
    @abstractmethod
    def load_model(self, name: str, tag: str, device: str) -> Dict[str, Any]: ...
    @abstractmethod
    def save_dataframe(self, df: Any, name: str) -> Path: ...
    @abstractmethod
    def load_dataframe(self, name: str) -> Any: ...
    @abstractmethod
    def save_json(self, data: Dict[str, Any], name: str) -> Path: ...
    @abstractmethod
    def load_json(self, name: str) -> Dict[str, Any]: ...
    @abstractmethod
    def get_artifact_path(self, name: str) -> Path: ...

class PipelineComponent(ABC):
    """Interface for ETL pipeline steps."""
    @abstractmethod
    def execute(self) -> None: ...

class StreamingSource(ABC):
    """Interface for data streaming."""
    @abstractmethod
    def __len__(self) -> int: ...
    @abstractmethod
    def __iter__(self): ...