from pathlib import Path
from typing import List

from ..foundation.configs import HydraConfigLoader, load_app_context
from ..foundation.interfaces import Registry, TelemetryObserver, PipelineComponent
from ..domain.vo import ETLConfig, ICDConfig, CNNConfig
from ..domain.entities import InterventionModelEntity, ICDModelEntity
from ..infrastructure.registry import FileSystemRegistry
from ..infrastructure.telemetry import RichTelemetryObserver
from ..infrastructure.datasource import HDF5StreamingSource, ParquetSource
from ..infrastructure.networks import GFINet_CNN

# New Refactored Service Imports
from ..services.etl.service import ETLService
from ..services.etl.components.assembler import FeatureAssembler
from ..services.etl.components.tensor import TensorConverter
from ..services.etl.components.labels import LabelGenerator
from ..services.training.automatic_icd_coding.service import ICDService
from ..services.training.predict_intervention.service import InterventionService

class AppFactory:
    """
    Factory class to assemble components and services (Dependency Injection).
    """
    def __init__(self, config_name: str = "config", config_path: str = "configs"):
        self.loader = HydraConfigLoader(config_name=config_name, config_path=config_path)
        self.raw_cfg = self.loader.load()
        self.ctx = load_app_context(self.raw_cfg)

    def create_registry(self) -> Registry:
        path = self.raw_cfg.get("logging", {}).get("artifacts_dir", "artifacts")
        return FileSystemRegistry(base_dir=path)

    def create_telemetry(self) -> TelemetryObserver:
        return RichTelemetryObserver()

    def create_etl_service(self) -> ETLService:
        etl_cfg = self.ctx.etl
        cnn_cfg = self.ctx.cnn
        icd_cfg = self.ctx.icd
        registry = self.create_registry()
        observer = self.create_telemetry()
        
        assembler = FeatureAssembler(etl_cfg, registry, observer)
        label_gen = LabelGenerator(etl_cfg, registry, observer)
        
        # Fixed: Added icd_config argument
        tensor_converter = TensorConverter(
            etl_config=etl_cfg,
            cnn_config=cnn_cfg,
            icd_config=icd_cfg,
            registry=registry,
            observer=observer
        )
        
        components: List[PipelineComponent] = [
            assembler,
            label_gen,
            tensor_converter
        ]
        
        return ETLService(registry, observer, components)

    def create_icd_service(self) -> ICDService:
        cfg = self.ctx.icd
        # etl_cfg = self.ctx.etl  # Unused in new H5 flow
        registry = self.create_registry()
        observer = self.create_telemetry()
        
        # Updated: ICD Service now reads from H5 files generated by TensorConverter
        # Config should point to data/cache and prefix "train_coding"
        cache_dir = Path(cfg.data.data_cache_dir)
        prefix = cfg.data.input_h5_prefix
        
        train_path = cache_dir / f"{prefix}_train.h5"
        val_path = cache_dir / f"{prefix}_val.h5"
        test_path = cache_dir / f"{prefix}_test.h5"

        # Note: We use label_key="y" for ICD training (Partial Label)
        try:
            train_source = HDF5StreamingSource(train_path, label_key="y")
            val_source = HDF5StreamingSource(val_path, label_key="y")
            test_source = HDF5StreamingSource(test_path, label_key="y") if test_path.exists() else None
        except Exception as e:
            observer.log("WARNING", f"Factory: Could not initialize ICD H5 sources ({e}). Ensure ETL has run.")
            train_source = None
            val_source = None
            test_source = None
        
        return ICDService(
            config=cfg,
            registry=registry,
            observer=observer,
            train_source=train_source,
            val_source=val_source,
            test_source=test_source
        )

    def create_intervention_service(self) -> InterventionService:
        cfg = self.ctx.cnn
        registry = self.create_registry()
        observer = self.create_telemetry()
        
        # Intervention Service reads from ICD Augmented H5 files (train_intervention)
        cache_dir = Path(cfg.data.data_cache_dir)
        prefix = cfg.data.input_h5_prefix 
        train_path = cache_dir / f"{prefix}_train.h5"
        val_path = cache_dir / f"{prefix}_val.h5"
        
        try:
            # Note: For Intervention, we expect 'y' to be ventilation label (handled by ICDService generation)
            train_source = HDF5StreamingSource(train_path, seq_len=cfg.seq_len)
            val_source = HDF5StreamingSource(val_path, seq_len=cfg.seq_len)
            vocab_sizes = train_source.get_real_vocab_sizes()
            
            if len(train_source) > 0:
                dummy = train_source[0]
                num_channels = dummy.x_num.shape[0]
                icd_dim = dummy.x_icd.shape[0] if dummy.x_icd is not None else 0
            else:
                num_channels = 0
                icd_dim = 0
        except Exception as e:
            observer.log("WARNING", f"CNN Factory: Could not initialize data sources ({e}). Using dummy dims.")
            train_source = None
            val_source = None
            vocab_sizes = []
            num_channels = 1
            icd_dim = 0

        network = GFINet_CNN(
            in_chs=[num_channels],
            n_cls=4,
            vocab_sizes=vocab_sizes,
            icd_dim=icd_dim,
            embed_dim=cfg.embed_dim,
            cat_embed_dim=cfg.cat_embed_dim,
            head_drop=cfg.dropout,
            tcn_drop=cfg.tcn_dropout,
            kernel=cfg.tcn_kernel_size,
            layers=cfg.tcn_layers
        )
        
        entity = InterventionModelEntity(network)
        
        return InterventionService(
            config=cfg,
            registry=registry,
            observer=observer,
            entity=entity,
            train_dataset=train_source,
            val_dataset=val_source
        )